# This is the InnovaSea Vemco Receiver Offload module(VRO) proglet initialization file
#
# This file is used to configure proglet specific parameters,
# configuration parameters take the format:
#              <attribute>: <value>
#
# The Max VR4 Offload Seconds attribute determines how long the proglet will
# attempt to offload VR4 data
#		n - maximum seconds to attempt a VR4 offload.
MAX_VR4_OFFLOAD_SECS: 1800

# The Max VRO File Transfer Seconds attribute determines how long the proglet will
# attempt to transfer a VRO file
#		n - maximum seconds to attempt a VRO file transfer.
MAX_VRO_FILE_TRANSFER_SECS: 120

# The Dectivate VR4 Meters attribute determines how far outside of a watch circle
# a VR4 becomes deactivated, flying outside of the watch circle by this distance
# and back into the watch circle will reactivate the VR4
#		n - meters required to be outside of a watch circle to deactivate a VR4.
DEACTIVATE_VR4_METERS: 20

# The VRO Power Down Meters attribute determines if the VRO will be powered down
# between VR4s.  If the next VR4 is greater than VRO_POWER_DOWN_METERS away
# power will be removed from the VRO until the next watch circle is entered
#		n - meters away from the next VR4, > n power down VRO
VRO_POWER_DOWN_METERS: 50


# #################################################################################
# The following parameters should only be changed when directed by Teledyne support
# #################################################################################

# The Diag Level parameter is used to capture diagnostic information, this should only
# be changed at Teledynes request.  When the diag level is > 0, output is generated to
# the science terminal and the science NLG file.
#		0 - DIAG_LEVEL_OFF, normal mode of operation, errors are reported.
#		1 - DIAG_LEVEL_1,   proglet trace info.
#		2 - DIAG_LEVEL_2,   DIAG_LEVEL1 + VRO message tracing.
DIAG_LEVEL: 0

# The Number of Errors attribute determines how many errors will be detected before
# a failing status is returned and a restart is generated.
#		n - Number of acceptable errors.
NUM_ERRORS: 0

# The Power Wait Seconds attribute determines how long the proglet waits before communicating
# with the VRO after enabling power.
#		n - seconds to wait before accessing the VRO after enabling power.
POWER_WAIT_SECS: 10

# The Command Response Wait Seconds attribute determines how long the proglet will
# wait for the command response
#		n - maximum seconds to wait for the command response before generating an error.
CMD_RESPONSE_MAX_WAIT_SECS: 5

# The Retry Pause Seconds attribute determines how often the proglet will
# wait before reattempting a CLOCK or STATUS message
#		n - seconds to wait before reattempting.
MSG_RETRY_PAUSE_SECS: 5

# The VR4 Test Pause Seconds attribute determines how often the proglet will
# test if a VR4 is within range
#		n - seconds to wait between tests for a VR4 in range.
VR4_TEST_PAUSE_SECS: 120

# The Sync Clock attribute determines if the proglet updates the time on the VRO
#		n - 0 = do not update the device time, 1 = update the device time.
SYNC_CLOCK: 1

# The Max Cancel Seconds attribute determines how long the proglet will wait
# for a successful CANCEL response
#		n - maximum seconds to wait for a successful CANCEL response
MAX_CANCEL_SECS: 5

# The Stop Pause Seconds attribute determines how long the proglet will wait
# after receiving the SHUTDOWN response before removing device power
#		n - maximum seconds to wait before removing device power
STOP_PAUSE_SECS: 30

# The Max Modem Initialization Seconds attribute determines how long the proglet will
# wait for the local modem to initialize
#		n - maximum seconds to wait for local modem initialization.
MAX_LOCAL_MODEM_INITIALIZATION_SECS: 20
