# EXTCTL.INI
# Maximum number of variables one can be subscribed to is 64 by default

mp # MISSION PARAMS SECTION


os # OUTPUT SENSORS SECTION

sci_generic_c nodim                             #0 Status report sample status


is # INPUT SENSORS SECTION

m_depth m                                       #1
cc_final_depth_state_mode enum                  #2 diving or climbing (1 or 2)
c_dive_target_depth m                           #3
sci_generic_a nodim                             #4 0-Disable 1-Dive 2-climb
sci_generic_b nodim								#5 Sampling Depth
sci_generic_d nodim			                    #6 Sample number

baud # BAUDRATE CONTROL
9600

packet_size # FILE READ PACKET SIZE CONTROL
500