# uRider.ini
# This is the Rockland Scientific MicroRider (MICRORIDER) proglet initialization file
#
# This file is used to configure proglet specific parameters,
# configuration parameters take the format:
#              <attribute>: <value>
#
# NOTE: MicroRider ISDP file support
#       To generate MicroRider ISDP files
#         * The MicroRider must be a DL3 rev3 with ISDP support, '/usr/local/bin/mergeqfiles' must exist
#         * The MicroRider must have ISDP support enabled, '/usr/local/etc/p113-daq.ini' "enable-isdp = TRUE"
#         * SENSOR_TYPE must be set to 2
#         * ISDP_MAX_FILE_SIZE_BYTES must be > 0
#         * The MicroRider 'sample' behavior must be enabled at the surface, 'state_to_sample' 8-15
#
#       The state of the file transfer can be monitored using sensor 'sci_microRider_file_state'
#          * 0-inactive
#          * 1-processing
#          * 2-process complete
#          * 3-process error
#
#       The ISDP file, '*.mri', will be located in 'science/logs'
#
#       When testing using "loadmission sci_on.mi", setting sensor 'x_surface_active' to '1'
#       will activate the MicroRider proglet surface behavior, download the merged 'q' files
#       from the MicroRider, and generate a 'science/logs/*.mri' file.

# The MicroRider Sensor Type parameter tells the proglet the device type.  This is
# necessary for specific device messages and state machine transitions
#		0 - MicroRider(1000), Persistor based, "Persistor CF2 SN:xxxxx BIOS:x.xx PicoDOS:x.xx"
#		1 - MicroRider(DL-3), Linux based, "p113r01-xxx login: debian (automatic login)"
#		2 - MicroRider(DL-3 with ISDP), Linux based, "p113r03-xxx login: debian (automatic login)"
SENSOR_TYPE: 2

# The MicroRider Powerup Prompt Retry Count parameter sets the number of retries for
# the device to generate a powerup prompt, 0-255.
#		n - maximum number of prompt retries
POWERUP_PROMPT_RETRY_COUNT: 3

# The MicroRider Max ISDP File Size Bytes is the maximum amount of data
# requested from the device in a single ISDP file.
#		n - maximum size of ISDP file requested
ISDP_MAX_FILE_SIZE_BYTES: 20000

# The MicroRider Max ISDP File Transfer Time Secs is the maximum amount of time,
# in seconds, that the ISDP file transfer can take.  The proglet will stop the
# file transfer if it is taking too long.
#		n - maximum seconds to transfer an ISDP file
ISDP_MAX_FILE_XFER_TIME_SECS: 180

# The MicroRider(DL-3 specific) Initial Status Delay tells the proglet to wait this
# long before querying the device status.
#		n - seconds to wait prior to sending initial status query message
DL3_INITIAL_STATUS_DELAY_SECS: 150

# The MicroRider(DL-3 specific) Status Interval Seconds tells the proglet how often
# to query the device status. Internal status data is only updated every 90 seconds,
# using a value < 90 is not recommended.
#		n - seconds between status query messages
DL3_STATUS_INTERVAL_SECS: 300

# The MicroRider(DL-3 specific) Max Status Response Wait Seconds tells the proglet
# how long to wait for the Status Response data.
#		n - seconds to wait for the status response data
DL3_MAX_STATUS_RESPONSE_WAIT_SECS: 10

# The Max Message Wait Seconds attribute determines how long the proglet
# will wait for a Verbose Console Output message. The absence of a message within
# this time is an indication that the MicroRider's internal flash memory is full.
#		n - maximum seconds to wait for a Verbose Console Output message
MAX_MESSAGE_WAIT_SECS: 60

# The Maximum Number of messages to store sets the limit for the number of messages
# stored in the 'xxxxxxxx.mrd' files, per proglet start.  The file may contain more
# than STORE_MAX_MSGS if there are multiple proglet starts within a segment.
#		n - store 'n' mesages maximum to the 'xxxxxxxx.mrd' file.
#           a value of -1 indicates no maximum
STORE_MAX_MSGS: -1

# #################################################################################
# The following parameters should only be changed when directed by Teledyne support
# #################################################################################

# The Diag Level parameter is used to capture diagnostic information, this should only
# be changed at Teledynes request.  When the diag level is > 0, output is generated to
# the science terminal and the science NLG file.
#		0 - DIAG_LEVEL_OFF, normal mode of operation, errors are reported.
#		1 - DIAG_LEVEL_1,   proglet trace info.
#		2 - DIAG_LEVEL_2,   DIAG_LEVEL1 + message tracing.
#		3 - DIAG_LEVEL_3,   DIAG_LEVEL_2 with output to glider.
DIAG_LEVEL: 0

# The Number of Errors attribute determines how many errors will be detected before
# a failing status is returned and a restart is generated.
#		n - Number of acceptable errors.
NUM_ERRORS: 0

# The Power Wait Seconds attribute determines how long the proglet waits before communicating
# with the device after enabling power.  This may need to be increased based on device bootup
# time.  A "state 'WAIT_INITIAL_PROMPT', no initial prompt" is an indication of the issue.
#		n - seconds to wait before accessing the device after enabling power.
POWER_WAIT_SECS: 60

# The Command Prompt Wait Seconds attribute determines how long the proglet will
# wait for the command prompt
#		n - maximum seconds to wait for the command prompt before generating an error.
CMD_PROMPT_MAX_WAIT_SECS: 10

# The Sync Clock attribute determines if the proglet updates the time on the device
#		n - 0 = do not update the device time, 1 = update the device time.
SYNC_CLOCK: 1

# The Stop Sampling Max Wait Seconds attribute determines how long the proglet
# will wait for a response before removing power from the device
#		n - maximum seconds to wait for a response prompt before removing power
STOP_MAX_WAIT_SECS: 10
