# EXTCTL.INI
# Maximum number of variables that can be subscribed to is 64
#UVP6

mp # MISSION PARAMS SECTION


os # OUTPUT SENSORS SECTIONS

sci_generic_a nodim	#0 initial status bit0-glider token, bit1-sensor token
sci_generic_b nodim #1 Received a valid time from glider
sci_generic_c nodim	#2 LPM line count
sci_generic_d nodim #3 Last depth seen from UVP6

is # INPUT SENSORS SECTION

m_present_time timestamp
m_depth m
cc_final_depth_state_mode enum	#1-diving, 2-climbing, 3-hovering


baud # BAUDRATE CONTROL
38400

packet_size # FILE READ PACKET SIZE CONTROL
500
