# This is the RBR Tridente Eco puck (rbrtridente) proglet initialization file
# It supports 1, 2, and 3 channel devices
#
# The device must output data in one of the following formats (1, 2, or 3 channel)
#
# What device gives back
# time ch1Signal ch2Signal ch3Signal
# 0, 1.5, 56.8246280, 126.114352
# 500, 1.5, 56.8185880, 126.106472
# 1000, 1.5, 56.8207120, 125.971912
# 1500, 1.5, 56.8245960, 126.072888
#
# This file is used to configure device specific parameters,
# configuration parameters take the format:
#              < attribute>: <value>

## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##
# Set the parameters based on the Tridente device. Specific device info is required.
## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##

# The Serial Number can be found on the device
SERIAL_NUM : 235281

# The Number of Channels, found on the calibration sheet
NUM_CHANNELS : 3

# Channel    Type		Label
# 1 ,        turb21,    backscatter_00
# 2 ,        fluo45,    chlorophyll_00
# 3 ,        fluo46,    fdom_00

# Channel #1 Optic Type, Required
#   type  optics
#     0 ,  Chlorophyll a,
#     1 ,  CDOM/FDOM,
#     2 ,  Phycocyanin,
#     3 ,  Phycoerythrin,
#     4 ,  Backscatter,
#     5 ,  Turbidity,
#   255 ,  other,
CH1_TYPE : 4

# Channel #2 Optic Type, Required for 2 or more channels
#       n - channel #2 type, refer to CH1_TYPE
CH2_TYPE : 0

# Channel #3 Optic Type, Required for 3 channels
#       n - channel #3 type, refer to CH1_TYPE
CH3_TYPE : 1
