# EXTCTL.INI
# Maximum number of variables that can be subscribed to is 64
#eDNA

mp # MISSION PARAMS SECTION


os # OUTPUT SENSORS SECTIONS


sci_generic_f nodim #0 Command Acknowledge
sci_generic_g nodim #1 RUN FIN seen

is # INPUT SENSORS SECTION

m_present_time timestamp
m_depth m
cc_final_depth_state_mode enum	#1-diving, 2-climbing, 3-hovering
sci_generic_a nodim	#0-off, 1-on dive, 2-on climb,3-on hover
sci_generic_b nodim #script start depth 
sci_generic_c nodim	#sample number
sci_generic_d nodim #below what depth to sample
sci_generic_e nodim #which script to run 1-hcl,2-flush,3-sample,4-rna,5-clean

baud # BAUDRATE CONTROL
115200

packet_size # FILE READ PACKET SIZE CONTROL
500
