# EXTCTL.INI
# Maximum number of variables one can be subscribed to is 64 by default

mp # MISSION PARAMS SECTION


os # OUTPUT SENSORS SECTION

sci_generic_c nodim                             #0 Status report parameter A
sci_generic_d nodim                             #1 Status report parameter B

is # INPUT SENSORS SECTION

m_present_time timestamp                        #2
m_depth m                                       #3
cc_final_depth_state_mode enum                  #4
x_mission_num nodim                             #5
m_lat lat                                       #6
m_lon lon                                       #7
c_dive_target_depth m                           #8
sci_generic_a nodim                             #9 Enable/Disable
cc_final_behavior_state enum                    #10
x_in_gliderdos bool                             #11
